### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by j-towns** [jonny-so/svae#1]
- [x] Three outputs in graphical model (Figure 3.), not four
- [ ] Define \eta_x(\theta) (referred to in equation (6))
- [ ] Label the subplots in Figure 1 with y_0, y_1, y_2
